Week16 task3
tarasov1812/social-network pull request #42
Opened 2023-10-05 17:46 UTC by tarasov1812

2023-10-13 18:50 UTC, burtovoy requested changes

2023-10-13 18:50 UTC, burtovoy commented on src/App.jsx
> +    axios.get('/posts.json')
Это нужно убрать из компоненты, в идеале сделать через createAsyncThunk

2023-10-13 18:50 UTC, burtovoy commented
плюс линтер что-то упал

2023-10-14 14:49 UTC, tarasov1812 commented
Исправил через createAsyncThunk в PostSlice.js

2023-10-16 13:22 UTC, merged