create action for creation posts
tarasov1812/social-network pull request #44
Opened 2023-10-23 16:03 UTC by tarasov1812

2023-10-25 14:46 UTC, burtovoy requested changes

2023-10-25 14:46 UTC, burtovoy commented on public/pictures.json
> +      "messageId": 16,
А для чего json этот меняется? Он нам по-идее не нужен

2023-10-25 14:46 UTC, burtovoy commented on src/components/Modal.jsx
> +    axios.post('/posts.json', requestBody, {
Запросов не должно быть в компонентах

2023-10-27 11:52 UTC, tarasov1812 commented
Аватарку в базу данных я переделаю в следующей ветке, что бы не было конфликтов

2023-10-30 23:29 UTC, merged